### ISSUE TITLE
RequestPermissionsAsync returns empty Dictionary

### ISSUE THREAD

**Issue by Cheesebaron** [jamesmontemagno/PermissionsPlugin#49]
## Bug Information

Version Number of Plugin: 1.2.1
Device Tested On: Samsung SM-G930F Android 7.0
Simulator Tested On: ?
Version of VS: VS2015
Version of Xamarin: ?
Versions of other things you are using: ?

### Steps to reproduce the Behavior
Can't reproduce locally, but got a single HockeyApp crash, where a call to RequestPermissionsAsync yielded an empty dict.

### Expected Behavior
Returned dict should always have some kind of status for requested key

### Actual Behavior
💥 

### Code snippet

```
var results = await permissions.RequestPermissionsAsync(Permission.Location);
status = results[Permission.Location];
```

Similar to your samples.

### Stack trace

Stack from HockeyApp:

```
Xamarin caused by: android.runtime.JavaProxyThrowable: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00021] in <e25755e715fc46b8b923cdc234258b18>:0 
  at NoiseSentinelApp.ViewModels.PublicSitesViewModel+<CheckPermissions>d__15.MoveNext () [0x00111] in <6056251c9e574471a64169ec91935eb0>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e25755e715fc46b8b923cdc234258b18>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <e25755e715fc46b8b923cdc234258b18>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <e25755e715fc46b8b923cdc234258b18>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <e25755e715fc46b8b923cdc234258b18>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <e25755e715fc46b8b923cdc234258b18>:0 
  at NoiseSentinelApp.ViewModels.PublicSitesViewModel+<<Initialize>b__10_0>d.MoveNext () [0x0006a] in <6056251c9e574471a64169ec91935eb0>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e25755e715fc46b8b923cdc234258b18>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in <e25755e715fc46b8b923cdc234258b18>:0 
  at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in <fbcbadf806a6438189c71b1942dc782b>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <fbcbadf806a6438189c71b1942dc782b>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <fbcbadf806a6438189c71b1942dc782b>:0 
  at (wrapper dynamic-method) System.Object:a589cd34-2cad-42ed-8843-c1f03f41d0d9 (intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by jamesmontemagno** [comment]
You should always check that it exists in the dictionary. 

If for some reason you don't have the permission in your manifest if I can't get access to the main activity: https://github.com/jamesmontemagno/PermissionsPlugin/blob/master/src/Plugin.Permissions.Android/PermissionsImplementation.cs#L130

**Comment by jamesmontemagno** [comment]
Well actually it could be that it isn't in your manifest.... would be the opposite.
I could probably change the check so it adds all them to the list and then updates them... Should never happen as long as they are in your manifest.

**Comment by Cheesebaron** [comment]
Well it is the only time I've experienced this happening. Not even my device. I've guarded against this and just return Unknown when it happens.

Can't see why it would be empty though.

**Comment by jamesmontemagno** [comment]
Going to close and document about the plan that you should check to be sure.
