### ISSUE TITLE
XF- Android: Exception when try to request Phone permission in Android OnCreate

### ISSUE THREAD

**Issue by ericbrunner** [jamesmontemagno/PermissionsPlugin#53]
**Target SDK:**

android:targetSdkVersion="25"

**Packages:**

```
<package id="Plugin.Permissions" version="2.0.1" targetFramework="monoandroid71" />
 <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Annotations" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.UI" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.Utils" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Design" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Fragment" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Media.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Transition" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.CardView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.Palette" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
    <package id="Xamarin.Build.Download" version="0.4.6" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms" version="2.3.4.247" targetFramework="monoandroid71" />
```

**Problem:**

I try to get the Phone permission in the OnCreate event, but I get an exception at that statement:

`var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] {Plugin.Permissions.Abstractions.Permission.Phone});`

**Exception:**

```
07-11 08:45:54.825 D/Mono    (20216): Assembly Ref addref Xamarin.Forms.Platform.Android[0x98bfc600] -> Xamarin.Android.Support.v4[0x98bfc1e0]: 3
An unhandled exception occured.

07-11 08:45:55.555 W/System.err(20216): java.io.InterruptedIOException: thread interrupted
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.okio.Okio$1.write(Okio.java:78)
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:60)
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1118)
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:951)
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:482)
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:235)
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
07-11 08:45:55.555 W/System.err(20216): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
07-11 08:45:55.555 W/System.err(20216): 	at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:114)
07-11 08:45:55.555 W/System.err(20216): 	at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:40)
07-11 08:45:55.555 W/System.err(20216): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
07-11 08:45:55.555 W/System.err(20216): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-11 08:45:55.555 W/System.err(20216): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-11 08:45:55.555 W/System.err(20216): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-11 08:45:55.555 W/System.err(20216): 	at java.lang.Thread.run(Thread.java:818)
```

**Code:**

```
        protected override async void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            UserDialogs.Init(() => (Activity) Forms.Context);

            CrossVersionTracking.Current.Track();

            BootstrapHockeyApp();

            // Set the current instance of MainActivity.
            CurrentActivity = this;
            global::Xamarin.Forms.Forms.Init(this, bundle);

            AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;
            TaskScheduler.UnobservedTaskException += TaskScheduler_UnobservedTaskException;


            try
            {
                var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Plugin.Permissions.Abstractions.Permission.Phone);
                if (status != PermissionStatus.Granted)
                {
                    if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Plugin.Permissions.Abstractions.Permission.Phone))
                    {
                        DialogNotify("Need phone permission", "Gunna need that phone permission");
                    }

                    var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] {Plugin.Permissions.Abstractions.Permission.Phone});
                    status = results[Plugin.Permissions.Abstractions.Permission.Phone];
                }

                if (status == PermissionStatus.Granted)
                {
                    await BootApplication();
                }
                else if (status != PermissionStatus.Unknown)
                {
                    DialogNotify("Permission Denied", "Can not continue, try again.");
                }
            }
            catch (Exception ex)
            {
                await MetricsManagerHelper.Instance.SendExceptionToApplicationInsightsAsync(ex).ConfigureAwait(true);
            }
        }


        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            global::ZXing.Net.Mobile.Forms.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
```

**Comment by jamesmontemagno** [comment]
What other packages do you have installed? This exception is clearly from okhttp.

**Comment by ericbrunner** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Acr.Support" version="2.1.0" targetFramework="monoandroid71" />
  <package id="Acr.UserDialogs" version="6.3.10" targetFramework="monoandroid71" />
  <package id="AndHUD" version="1.2.0" targetFramework="monoandroid71" />
  <package id="HockeySDK.Xamarin" version="4.1.1" targetFramework="monoandroid71" />
  <package id="Microsoft.Azure.Mobile.Client" version="3.1.0" targetFramework="monoandroid71" />
  <package id="Microsoft.Azure.Mobile.Client.SQLiteStore" version="3.1.0" targetFramework="monoandroid71" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="monoandroid60" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="monoandroid60" />
  <package id="Microsoft.CSharp" version="4.3.0" targetFramework="monoandroid71" />
  <package id="Microsoft.Data.Edm" version="5.8.2" targetFramework="monoandroid71" />
  <package id="Microsoft.Data.OData" version="5.8.2" targetFramework="monoandroid71" />
  <package id="Microsoft.Data.Services.Client" version="5.8.2" targetFramework="monoandroid71" />
  <package id="Microsoft.Net.Http" version="2.2.29" targetFramework="monoandroid60" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="monoandroid71" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="NETStandard.Library" version="1.6.1" targetFramework="monoandroid71" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="monoandroid71" />
  <package id="PCLCrypto" version="2.0.147" targetFramework="monoandroid71" />
  <package id="PCLStorage" version="1.0.2" targetFramework="monoandroid71" />
  <package id="PInvoke.BCrypt" version="0.3.152" targetFramework="monoandroid71" />
  <package id="PInvoke.Kernel32" version="0.3.152" targetFramework="monoandroid71" />
  <package id="PInvoke.NCrypt" version="0.3.152" targetFramework="monoandroid71" />
  <package id="PInvoke.Windows.Core" version="0.3.152" targetFramework="monoandroid71" />
  <package id="Plugin.CurrentActivity" version="1.0.1" targetFramework="monoandroid71" />
  <package id="Plugin.Permissions" version="2.0.1" targetFramework="monoandroid71" />
  <package id="Plugin.VersionTracking" version="1.0.1" targetFramework="monoandroid71" />
  <package id="Refractored.XamForms.PullToRefresh" version="1.1.0" targetFramework="monoandroid71" />
  <package id="Splat" version="1.6.2" targetFramework="monoandroid71" />
  <package id="SQLitePCLRaw.bundle_green" version="1.1.2" targetFramework="monoandroid71" />
  <package id="SQLitePCLRaw.core" version="1.1.2" targetFramework="monoandroid71" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.android" version="1.1.2" targetFramework="monoandroid71" />
  <package id="SQLitePCLRaw.provider.e_sqlite3.android" version="1.1.2" targetFramework="monoandroid71" />
  <package id="System.AppContext" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Collections" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.ComponentModel.EventBasedAsync" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Console" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Dynamic.Runtime" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Globalization" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.IsolatedStorage" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Linq" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Linq.Queryable" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Net.Http" version="4.3.1" targetFramework="monoandroid71" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Net.Requests" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Reflection" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Serialization.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Spatial" version="5.8.2" targetFramework="monoandroid71" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Threading" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="monoandroid71" />
  <package id="Validation" version="2.4.9" targetFramework="monoandroid71" />
  <package id="WindowsAzure.Storage" version="8.1.0" targetFramework="monoandroid71" />
  <package id="Xam.Plugin.Connectivity" version="2.3.0" targetFramework="monoandroid71" />
  <package id="Xam.Plugin.DeviceInfo" version="2.1.2" targetFramework="monoandroid71" />
  <package id="Xam.Plugin.Geolocator" version="4.0.0.55-beta" targetFramework="monoandroid71" />
  <package id="Xam.Plugin.Media" version="2.6.3.6-beta" targetFramework="monoandroid71" />
  <package id="Xam.Plugins.Messaging" version="3.2.1" targetFramework="monoandroid71" />
  <package id="Xam.Plugins.Vibrate" version="2.0.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Annotations" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.UI" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.Utils" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Design" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Fragment" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Media.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Transition" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.CardView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.Palette" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Auth" version="1.3.2.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Build.Download" version="0.4.6" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms" version="2.3.4.247" targetFramework="monoandroid71" />
  <package id="ZXing.Net.Mobile" version="2.1.47" targetFramework="monoandroid71" />
  <package id="ZXing.Net.Mobile.Forms" version="2.1.47" targetFramework="monoandroid71" />
</packages>
```

**Comment by ericbrunner** [comment]
Maybe a HockeyApp issue. Have to investigate. Will try to move BootStrap HockeyApp after the Request Permission code. It could be that the HockeyApp UpdateManager gets in timeout...

**Comment by jamesmontemagno** [comment]
Couldn't repo: https://gist.github.com/jamesmontemagno/b9cd8d2271685b3f4ba28d3410ea7929

I would maybe refactor some of that code so less stuff is in your OnCreate() in general maybe other stuff hasn't been initialized.

**Comment by ericbrunner** [comment]
@jamesmontemagno Sorry to see that you closed the issue. I tried your code in my Xamarin.Forms Android project and failed again. I commented the HockeyApp UpdateManager to get rid of any HA related exception.

Now I get that exception: https://gist.github.com/ericbrunner/bb991e6eaae39a2996ad53d2cf2b181f
Code of XF Android: https://gist.github.com/ericbrunner/729e3ac80663a9d1a0f1b4e6c75ff108

**Comment by jamesmontemagno** [comment]
May I recommend trying file->new and giving it a go, rest assured it is not me even by this bug as you may be hanging your UI and not letting Xamarin.Forms fully initialize things.

Try to use other forms of await such as ContinueWith perhaps so you aren't blocking OnCreate from finishing.. My assumption is that you are completely blocking your app from starting up and from letting forms finish initializing.

**Comment by ericbrunner** [comment]
I tried that way in `OnCreate `but same result. As you wrote I guess `OnCreate `is a tricky area for that.

I put code something like that in the `ctor `of the `App.cs` in **PCL** and it works. Thanks for your support!

```
public App(bool databaseSchemaChanged = false)
        {
            IsStarted = true;
            IsApplicationVisible = false;


            if (Device.RuntimePlatform == Device.Android)
            {
                CheckPermissions(Permission.Phone).ContinueWith(async t =>
                {
                    var phonePermission = t.Result;

                    if (phonePermission)
                    {
                        LaunchApplication(databaseSchemaChanged);
                    } else
                    {
                        
                        await Acr.UserDialogs.UserDialogs.Instance.AlertAsync("App must be close due to rejected permission", "Permission Error");
                        DependencyService.Get<IApplicationClose>().CloseApp();
                    }
                });
            }
            else
            {
                LaunchApplication(databaseSchemaChanged);
            }
        }
```

**Comment by ericbrunner** [comment]
Just wanne share a full working code if anyone comes along that way: https://gist.github.com/ericbrunner/822b950c3be01e9a9c62df7ae9f32d7e
