### ISSUE TITLE
App crash on Android

### ISSUE THREAD

**Issue by ilber** [jamesmontemagno/PermissionsPlugin#78]
App crashing randomly with this exception:

Exception:[An attempt was made to transition a task to a final state when it had already completed.];   at System.Threading.Tasks.TaskCompletionSource`1[TResult].SetResult (TResult result) [0x00013] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
  at Plugin.Permissions.PermissionsImplementation.OnRequestPermissionsResult (System.Int32 requestCode, System.String[] permissions, Android.Content.PM.Permission[] grantResults) [0x000ff] in <04a764704c87461cb5448972b243403b>:0 
  at ***.Droid.Views.Base.AppBaseActivity`1[T].OnRequestPermissionsResult (System.Int32 requestCode, System.String[] permissions, Android.Content.PM.Permission[] grantResults) [0x0000e] in <37670d6bfa6d48e782e5d4499b12d466>:0 
  at Android.Support.V4.App.FragmentActivity.n_OnRequestPermissionsResult_IarrayLjava_lang_String_arrayI (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 requestCode, System.IntPtr native_permissions, System.IntPtr native_grantResults) [0x00031] in <1e89c43d3c7d48b5ba69bfc0b1bdf114>:0 
  at (wrapper dynamic-method) System.Object:e61ff29f-a1ec-4914-81db-4486c7abb9bf (intptr,intptr,int,intptr,intptr)
Exception:[Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.]; 
  --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
android.runtime.JavaProxyThrowable: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
  at System.Threading.Tasks.TaskCompletionSource`1[TResult].SetResult (TResult result) [0x00013] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
  at Plugin.Permissions.PermissionsImplementation.OnRequestPermissionsResult (System.Int32 requestCode, System.String[] permissions, Android.Content.PM.Permission[] grantResults) [0x000ff] in <04a764704c87461cb5448972b243403b>:0 
  at ***.Droid.Views.Base.AppBaseActivity`1[T].OnRequestPermissionsResult (System.Int32 requestCode, System.String[] permissions, Android.Content.PM.Permission[] grantResults) [0x0000e] in <37670d6bfa6d48e782e5d4499b12d466>:0 
  at Android.Support.V4.App.FragmentActivity.n_OnRequestPermissionsResult_IarrayLjava_lang_String_arrayI (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 requestCode, System.IntPtr native_permissions, System.IntPtr native_grantResults) [0x00031] in <1e89c43d3c7d48b5ba69bfc0b1bdf114>:0 
  at (wrapper dynamic-method) System.Object:e61ff29f-a1ec-4914-81db-4486c7abb9bf (intptr,intptr,int,intptr,intptr)
	at md50e0e0292c2f325605a81380330afb90c.AppBaseActivity_1.n_onRequestPermissionsResult(Native Method)
	at md50e0e0292c2f325605a81380330afb90c.AppBaseActivity_1.onRequestPermissionsResult(AppBaseActivity_1.java:65)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6567)
	at android.app.Activity.dispatchActivityResult(Activity.java:6446)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
	at android.app.ActivityThread.-wrap16(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

## Bug Information

Version Number of Plugin: 2.2.1
Device Tested On: Nexus 6
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior

No clear steps. It just happens.

### Expected Behavior

Should not crash :)

### Actual Behavior

Is crashing the app

### Code snippet

`public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
		{
			base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
			
			PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
		}`

**Comment by jamesmontemagno** [comment]
You are most likely calling permission requests on multiple threads or tasks. You can't do that. Put a semiphore or something else in place.

**Comment by ilber** [comment]
Thank you @jamesmontemagno .

**Comment by ilber** [comment]
Even after locking the execution of the code 
`PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);`
I still receive the same crash. Something else that could cause this crash?
